# Generated by Django 6.1.1 on 2026-09-30 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('body', models.TextField(help_text='Full text (paste your LinkedIn post here)')),
                ('excerpt', models.TextField(blank=True, help_text='Auto-filled from body if empty; used for RAG + cards')),
                ('linkedin_url', models.URLField(blank=True, null=True, unique=True)),
                ('linkedin_embed_html', models.TextField(blank=True, help_text='Sanitized LinkedIn iframe. Auto-cleaned on save.')),
                ('published_at', models.DateField(blank=True, db_index=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=2000)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('result', models.CharField(blank=True, help_text='e.g. CGPA 3.30/4.00', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('bullets', models.TextField(help_text='One achievement per line')),
            ],
            options={
                'ordering': ['order', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('title', models.CharField(help_text='e.g. R&D Engineer — Routing / Embedded Networking', max_length=200)),
                ('summary', models.TextField(help_text='Personal summary shown at top of page')),
                ('photo', models.ImageField(help_text='Required. Square photo works best.', upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('location', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('language', 'Languages'), ('os', 'Operating Systems'), ('networking', 'Networking'), ('framework', 'Frameworks & Tools'), ('cs', 'Core CS'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('proficiency', models.IntegerField(default=3, help_text='1-5')),
            ],
            options={
                'ordering': ['order', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('github_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.skill')),
            ],
            options={
                'ordering': ['order', '-id'],
                'abstract': False,
            },
        ),
    ]
