# Generated by Django 6.1.1 on 2026-09-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credential_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated skills', max_length=500),
        ),
    ]
