# Generated by Django 6.1.1 on 2026-10-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_course_credential_id_course_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Languages'), ('os', 'Operating Systems'), ('networking', 'Networking'), ('framework', 'Frameworks & Tools'), ('cs', 'Core CS'), ('ai', 'AI / Machine Learning'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
    ]
